### ISSUE TITLE
cdnjs

### ISSUE THREAD

**Issue by JoeHana** [mckamey/cssuseragent#1]
I would love to see your script available via CDN. Would you mind submitting it there: https://github.com/cdnjs/cdnjs?

**Comment by mckamey** [comment]
@JoeHana, I actually just looked into this yesterday and it looks like cdnjs is no longer a straightforward process:

https://github.com/cdnjs/cdnjs/issues/3638

The old way (manual pull request) is deprecated and the new way (npm / git auto-update) isn't actually working yet.

Note to self: when it does work, I want to use `cssuseragent` as the lib slug so that [it matches bower](bower.io/search/?q=cssuseragent):

`ajax/libs/cssuseragent/2.1.28/cssua.min.js`

**Comment by mckamey** [comment]
https://github.com/cdnjs/cdnjs/commit/726e2079364fadb20ffb15f59d56d05666dd2bc7

**Comment by mckamey** [comment]
This finally got resolved.
